AirBnb.web/Controllers/AmenityController.cs
using AirBnb.Infrastructure.Data;
using Microsoft.AspNetCore.Mvc;
using AirBnb.Domain.Entities;
using Microsoft.AspNetCore.Mvc.Rendering;
using AirBnb.web.ViewModels;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics.CodeAnalysis;
using AirBnb.Application.Common.Interfaces;

namespace AirBnb.web.Controllers
{
    public class AmenityController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public AmenityController(IUnitOfWork unitOfWork) 
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
            var amenities = _unitOfWork.amenity.GetAll(includeProperties: "Villa");
            return View(amenities);
        }

        public IActionResult Create()
        {
            AmenityViewModel viewModel = new()
            {
                VillaList = _unitOfWork.villa.GetAll().Select(u => new SelectListItem
                {
                    Text = u.Name,
                    Value = u.Id.ToString()
                })
            };
            return View(viewModel);
        }

        [HttpPost]
        public IActionResult Create(AmenityViewModel obj) 
        {
            if (ModelState.IsValid ) 
            {
                _unitOfWork.amenity.Add(obj.amenity);
                _unitOfWork.Save();
                TempData["Success"] = "The amenity has been created";
                return RedirectToAction("Index");
            }

            obj.VillaList = _unitOfWork.villa.GetAll().Select(u => new SelectListItem
            {
                Text = u.Name,
                Value = u.Id.ToString()
            });
            return View(obj);
        }

        public IActionResult Update(int amenityId)
        {
            AmenityViewModel amenityViewModel = new()
            {
                VillaList = _unitOfWork.villa.GetAll().Select(u => new SelectListItem
                {
                    Text = u.Name,
                    Value = u.Id.ToString()
                }),

                amenity = _unitOfWork.amenity.Get(u=>u.Id == amenityId)
            };

            if (amenityViewModel.amenity == null) 
            {
                return RedirectToAction("Error","Home");
            }
            return View(amenityViewModel);
        }

        [HttpPost]
        public IActionResult Update(AmenityViewModel obj)
        { 
            if (ModelState.IsValid )
            {
                _unitOfWork.amenity.Update(obj.amenity);
                _unitOfWork.Save();
                TempData["Success"] = "The amenity has been updated";
                return RedirectToAction("Index");
            }

            obj.VillaList = _unitOfWork.villa.GetAll().Select(u => new SelectListItem
            {
                Text = u.Name,
                Value = u.Id.ToString()
            });
            return View(obj);
        }

        public IActionResult Delete(int amenityId)
        {
            AmenityViewModel amenityViewModel = new()
            {
                VillaList = _unitOfWork.villa.GetAll().Select(u => new SelectListItem
                {
                    Text = u.Name,
                    Value = u.Id.ToString()
                }),

                amenity = _unitOfWork.amenity.Get(u => u.Id == amenityId)
            };

            if (amenityViewModel.amenity == null)
            {
                return RedirectToAction("Error", "Home");
            }
            return View(amenityViewModel);
        }

        [HttpPost]
        public IActionResult Delete(AmenityViewModel amenityViewModel)
        {
            Amenity? dbObj = _unitOfWork.amenity.Get(u=>u.Id == amenityViewModel.amenity.Id);
            if (dbObj is not null)
            {
                _unitOfWork.amenity.Remove(dbObj);
                _unitOfWork.Save();
                TempData["Success"] = "The amenity has been Deleted";
                return RedirectToAction("Index");
            }

            amenityViewModel.VillaList = _unitOfWork.villa.GetAll().Select(u => new SelectListItem
            {
                Text = u.Name,
                Value = u.Id.ToString()
            });
            return View();
        }
    }
}

AirBnb.web/Controllers/VillaController.cs
using AirBnb.Application.Common.Interfaces;
using AirBnb.Domain.Entities;
using AirBnb.Infrastructure.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace AirBnb.web.Controllers
{
    public class VillaController : Controller
    {
        private readonly IUnitOfWork _unitOfWork; 
        private readonly IWebHostEnvironment _webHostEnvironment;

        public VillaController(IUnitOfWork unitOfWork, IWebHostEnvironment webHostEnvironment)
        {
            _unitOfWork = unitOfWork;
            _webHostEnvironment = webHostEnvironment;
        }

        public IActionResult Index()
        {   
            var villas = _unitOfWork.villa.GetAll();
            return View(villas);
        }

        public IActionResult Create() 
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Villa obj)
        {
            if (obj.Name == obj.Description)
            {
                ModelState.AddModelError("description","Description Cannot be same as Name");
            }
            if (ModelState.IsValid) 
            {
                if (obj.Image != null) 
                {
                    string fileName = Guid.NewGuid().ToString() + Path.GetExtension(obj.Image.FileName);
                    string imagePath = Path.Combine(_webHostEnvironment.WebRootPath,@"images\VillaImage");
                    using var fileStream = new FileStream(Path.Combine(imagePath, fileName), FileMode.Create);
                    obj.Image.CopyTo(fileStream);
                    obj.ImageUrl = @"\images\VillaImage\" + fileName;
                }
                else
                {
                    obj.ImageUrl = "https://placehold.co/600x400";
                }   
                _unitOfWork.villa.Add(obj);
                _unitOfWork.Save();
                return RedirectToAction("Index");
            }
            return View();   
        }

        public IActionResult Update(int villaId)
        {  
            Villa ?villa = _unitOfWork.villa.Get(villa => villa.Id == villaId);
            if (villa is null)
            {
                return RedirectToAction("Error","Home");
            }
            return View(villa);
        }

        [HttpPost]
        public IActionResult Update(Villa obj)
        {
            if (ModelState.IsValid && obj.Id>0)
            {   
                if (obj.Image != null)
                {
                    string fileName = Guid.NewGuid().ToString() + Path.GetExtension(obj.Image.FileName);
                    string imagePath = Path.Combine(_webHostEnvironment.WebRootPath,@"images\VillaImage\");

                    if (!string.IsNullOrEmpty(obj.ImageUrl))
                    {
                        var oldImagePath = Path.Combine(_webHostEnvironment.WebRootPath,obj.ImageUrl.TrimStart('\\'));

                        if (System.IO.File.Exists(oldImagePath))
                        {
                            System.IO.File.Delete(oldImagePath);    
                        }
                    }
                    using var fileStream = new FileStream(Path.Combine(imagePath,fileName),FileMode.Create);
                    obj.Image.CopyTo(fileStream);
                    obj.ImageUrl = @"\images\VillaImage\" + fileName;
                }
                else 
                {
                    obj.ImageUrl = "https://placehold.co/600x400";
                }

                _unitOfWork.villa.Update(obj);
                _unitOfWork.Save();
                TempData["success"] = "Villa has been updated Sucessfully!";
                return RedirectToAction("Index");
            }
            return View();
        }

        public IActionResult Delete(int villaId)
        {
            Villa? villa = _unitOfWork.villa.Get(villa => villa.Id == villaId);
            if (villa is null)
            {
                return RedirectToAction("Error", "Home");
            }
            return View(villa);
        }

        [HttpPost]
        public IActionResult Delete(Villa obj)
        {   
            Villa? dbObj = _unitOfWork.villa.Get(db => db.Id == obj.Id); 
            if (dbObj is not null)
            {
                _unitOfWork.villa.Remove(dbObj);
                _unitOfWork.Save();
                TempData["success"] = "Villa Deleted Sucessfully";
                return RedirectToAction("Index");
            }
            TempData["error"] = "Villa could not be Deleted !";
            return View();
        }
    }
}

AirBnb.web/Controllers/VillaNumberController.cs
using AirBnb.Infrastructure.Data;
using Microsoft.AspNetCore.Mvc;
using AirBnb.Domain.Entities;
using Microsoft.AspNetCore.Mvc.Rendering;
using AirBnb.web.ViewModels;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics.CodeAnalysis;
using AirBnb.Application.Common.Interfaces;

namespace AirBnb.web.Controllers
{
    public class VillaNumberController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public VillaNumberController(IUnitOfWork unitOfWork) 
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {   
            var villaNumbers = _unitOfWork.villaNumber.GetAll(includeProperties: "Villa");    
            return View(villaNumbers);
        }

        public IActionResult Create()
        {
            VillaNumberViewModel viewModel = new()
            {
                VillaList = _unitOfWork.villa.GetAll().Select(u => new SelectListItem
                {
                    Text = u.Name,
                    Value = u.Id.ToString()
                })
            };
            return View(viewModel);
        }

        [HttpPost]
        public IActionResult Create(VillaNumberViewModel obj) 
        {
            bool isNumberExists = _unitOfWork.villaNumber.Any(u=>u.Villa_Number == obj.VillaNumber.Villa_Number);

            if (ModelState.IsValid && !isNumberExists) 
            {
                _unitOfWork.villaNumber.Add(obj.VillaNumber);
                _unitOfWork.Save();
                TempData["Success"] = "The Villa Number has been created";
                return RedirectToAction("Index");
            }

            if (isNumberExists) 
            {
                TempData["Error"] = "This Villa Number already exists";
            }

            obj.VillaList = _unitOfWork.villa.GetAll().Select(u => new SelectListItem
            {
                Text = u.Name,
                Value = u.Id.ToString()
            });
            return View(obj);
        }

        public IActionResult Update(int villaNumberId)
        {
            VillaNumberViewModel villaNumberViewModel = new()
            {
                VillaList = _unitOfWork.villa.GetAll().Select(u => new SelectListItem
                {
                    Text = u.Name,
                    Value = u.Id.ToString()
                }),

                VillaNumber = _unitOfWork.villaNumber.Get(u=>u.Villa_Number == villaNumberId)
            };

            if (villaNumberViewModel.VillaNumber == null) 
            {
                return RedirectToAction("Error","Home");
            }
            return View(villaNumberViewModel);
        }

        [HttpPost]
        public IActionResult Update(VillaNumberViewModel obj)
        { 
            if (ModelState.IsValid )
            {
                _unitOfWork.villaNumber.Update(obj.VillaNumber);
                _unitOfWork.Save();
                TempData["Success"] = "The Villa Number has been updated";
                return RedirectToAction("Index");
            }

            obj.VillaList = _unitOfWork.villa.GetAll().Select(u => new SelectListItem
            {
                Text = u.Name,
                Value = u.Id.ToString()
            });
            return View(obj);
        }

        public IActionResult Delete(int villaNumberId)
        {
            VillaNumberViewModel villaNumberViewModel = new()
            {
                VillaList = _unitOfWork.villa.GetAll().Select(u => new SelectListItem
                {
                    Text = u.Name,
                    Value = u.Id.ToString()
                }),

                VillaNumber = _unitOfWork.villaNumber.Get(u => u.Villa_Number == villaNumberId)
            };

            if (villaNumberViewModel.VillaNumber == null)
            {
                return RedirectToAction("Error", "Home");
            }
            return View(villaNumberViewModel);
        }

        [HttpPost]
        public IActionResult Delete(VillaNumberViewModel villaNumberViewModel)
        {
            VillaNumber? dbObj = _unitOfWork.villaNumber.Get(u=>u.Villa_Number == villaNumberViewModel.VillaNumber.Villa_Number);
            if (dbObj is not null)
            {
                _unitOfWork.villaNumber.Remove(dbObj);
                _unitOfWork.Save();
                TempData["Success"] = "The Villa Number has been Deleted";
                return RedirectToAction("Index");
            }

            villaNumberViewModel.VillaList = _unitOfWork.villa.GetAll().Select(u => new SelectListItem
            {
                Text = u.Name,
                Value = u.Id.ToString()
            });
            return View();
        }
    }
}

AirBnb.web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en" data-bs-theme="dark">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AirBnb.web</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.1/css/bootstrap.min.css" integrity="sha512-Z/def5z5u2aR89OuzYcxmDJ0Bnd5V1cKqBEbvLOiUNWdg9PQeXVvXLI90SE4QOHGlfLqUnDNVAYyZi8UwUTmWQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="~/AirBnb.web.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.css" integrity="sha512-3pIirOrwegjM6erE5gPSwkUzO+3cTjpnV9lexlNZqvupR64iZBnOOTiiLPb9M36zpMScbmUNIcHUqKD47M719g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="/images/resort.png" style="width:35px"/></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Content Management
                            </a>
                            <ul class="dropdown-menu">
                                <li>
                                    <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                                </li>
                                <li>
                                    <a class="nav-link" asp-controller="Villa" asp-action="Index">Villa</a>
                                </li>
                                <li>
                                    <a class="nav-link" asp-controller="VillaNumber" asp-action="Index">Villa Number</a>
                                </li>
                                <li>
                                    <a class="nav-link" asp-controller="Amenity" asp-action="Index">Amenity</a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="">
        <main role="main" >
            <partial name="_Notification"/>
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - AirBnb.web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.3/js/bootstrap.bundle.min.js" integrity="sha512-7Pi/otdlbbCR+LnW+F7PwFcSDJOuUJB3OxtEHbg4vSMvzvJjde4Po1v4BR9Gdc9aXNUNFVUY+SK51wWT8WF0Gg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

AirBnb.web/Views/Shared/_Notification.cshtml
@if (TempData["error"] != null)
{
          <script src="~/lib/jquery/dist/jquery.min.js"></script>
          <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js" integrity="sha512-VEd+nq25CkR676O+pLBnDW09R7VQX9Mdiij052gVCp5yVH3jGtH70Ho/UUv4mJDsEdTvqRCFZg0NKGiojGnUCw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
          <script type="text/javascript">
                  toastr.error('@TempData["error"]')
          </script>
}
@if (TempData["success"] != null)
{
          <script src="~/lib/jquery/dist/jquery.min.js"></script>
          <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js" integrity="sha512-VEd+nq25CkR676O+pLBnDW09R7VQX9Mdiij052gVCp5yVH3jGtH70Ho/UUv4mJDsEdTvqRCFZg0NKGiojGnUCw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
          <script type="text/javascript">
                  toastr.success('@TempData["success"]')
          </script>
}