AirBnb.web/Controllers/VillaController.cs
using AirBnb.Application.Common.Interfaces;
using AirBnb.Domain.Entities;
using AirBnb.Infrastructure.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace AirBnb.web.Controllers
{
    public class VillaController : Controller
    {
        private readonly IUnitOfWork _unitOfWork; 
        private readonly IWebHostEnvironment _webHostEnvironment;

        public VillaController(IUnitOfWork unitOfWork, IWebHostEnvironment webHostEnvironment)
        {
            _unitOfWork = unitOfWork;
            _webHostEnvironment = webHostEnvironment;
        }

        public IActionResult Index()
        {   
            var villas = _unitOfWork.villa.GetAll();
            return View(villas);
        }

        public IActionResult Create() 
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Villa obj)
        {
            if (obj.Name == obj.Description)
            {
                ModelState.AddModelError("description","Description Cannot be same as Name");
            }
            if (ModelState.IsValid) 
            {
                if (obj.Image != null) 
                {
                    string fileName = Guid.NewGuid().ToString() + Path.GetExtension(obj.Image.FileName);
                    string imagePath = Path.Combine(_webHostEnvironment.WebRootPath,@"images\VillaImage");
                    using var fileStream = new FileStream(Path.Combine(imagePath, fileName), FileMode.Create);
                    obj.Image.CopyTo(fileStream);
                    obj.ImageUrl = @"\images\VillaImage\" + fileName;
                }
                else
                {
                    obj.ImageUrl = "https://placehold.co/600x400";
                }   
                _unitOfWork.villa.Add(obj);
                _unitOfWork.Save();
                return RedirectToAction("Index");
            }
            return View();   
        }

        public IActionResult Update(int villaId)
        {  
            Villa ?villa = _unitOfWork.villa.Get(villa => villa.Id == villaId);
            if (villa is null)
            {
                return RedirectToAction("Error","Home");
            }
            return View(villa);
        }

        [HttpPost]
        public IActionResult Update(Villa obj)
        {
            if (ModelState.IsValid && obj.Id>0)
            {   
                if (obj.Image != null)
                {
                    string fileName = Guid.NewGuid().ToString() + Path.GetExtension(obj.Image.FileName);
                    string imagePath = Path.Combine(_webHostEnvironment.WebRootPath,@"images\VillaImage\");

                    if (!string.IsNullOrEmpty(obj.ImageUrl))
                    {
                        var oldImagePath = Path.Combine(_webHostEnvironment.WebRootPath,obj.ImageUrl.TrimStart('\\'));

                        if (System.IO.File.Exists(oldImagePath))
                        {
                            System.IO.File.Delete(oldImagePath);    
                        }
                    }
                    using var fileStream = new FileStream(Path.Combine(imagePath,fileName),FileMode.Create);
                    obj.Image.CopyTo(fileStream);
                    obj.ImageUrl = @"\images\VillaImage\" + fileName;
                }
                else 
                {
                    obj.ImageUrl = "https://placehold.co/600x400";
                }

                _unitOfWork.villa.Update(obj);
                _unitOfWork.Save();
                TempData["success"] = "Villa has been updated Sucessfully!";
                return RedirectToAction("Index");
            }
            return View();
        }

        public IActionResult Delete(int villaId)
        {
            Villa? villa = _unitOfWork.villa.Get(villa => villa.Id == villaId);
            if (villa is null)
            {
                return RedirectToAction("Error", "Home");
            }
            return View(villa);
        }

        [HttpPost]
        public IActionResult Delete(Villa obj)
        {   
            Villa? dbObj = _unitOfWork.villa.Get(db => db.Id == obj.Id); 
            if (dbObj is not null)
            {
                _unitOfWork.villa.Remove(dbObj);
                _unitOfWork.Save();
                TempData["success"] = "Villa Deleted Sucessfully";
                return RedirectToAction("Index");
            }
            TempData["error"] = "Villa could not be Deleted !";
            return View();
        }
    }
}

AirBnb.web/Views/Villa/Create.cshtml
@model AirBnb.Domain.Entities.Villa

<div class="w-100 card border-0 p-4">
	<div class="card-header bg-sucess bg-gradient m-lg-0 py-3">
		<div class="row">
			<div class="col-12 text-center">
				<h2 class="text-white py-2">Villa list</h2>
			</div>
		</div>
	</div>
	<div class="card-body border p-4">
		<form method="post" class="row" enctype="multipart/form-data">
			<div class="p-3">
				<div class="form-floating py-1 col-12">
					<input asp-for="@Model.Name" class="form-control border shadow" />
					<label asp-for="@Model.Name" class="ms-2"></label>
					<span asp-validation-for="@Model.Name" class="text-danger"></span>
				</div>
				<div class="form-floating py-1 col-12">
					<input asp-for="@Model.Description" class="form-control border shadow" />
					<label asp-for="@Model.Description" class="ms-2"></label>
					<span asp-validation-for="@Model.Description" class="text-danger"></span>
				</div>
				<div class="form-floating py-1 col-12">
					<input asp-for="@Model.Price" class="form-control border shadow" />
					<label asp-for="@Model.Price" class="ms-2"></label>
					<span asp-validation-for="@Model.Price" class="text-danger"></span>
				</div>
				<div class="form-floating py-1 col-12">
					<input asp-for="@Model.Sqft" class="form-control border shadow" />
					<label asp-for="@Model.Sqft" class="ms-2"></label>
					<span asp-validation-for="@Model.Sqft" class="text-danger"></span>
				</div>
				<div class="form-floating py-1 col-12">
					<input asp-for="@Model.Occupancy" class="form-control border shadow" />
					<label asp-for="@Model.Occupancy" class="ms-2"></label>
					<span asp-validation-for="@Model.Occupancy" class="text-danger"></span>
				</div>
				<div class="form-floating py-1 col-12">
					<input asp-for="@Model.ImageUrl" hidden class="form-control border shadow" />
					<input asp-for="@Model.Image" class="form-control border shadow" />
					<label asp-for="@Model.ImageUrl" class="ms-2 "></label>
					<span asp-validation-for="@Model.ImageUrl" class="text-danger"></span>
				</div>
				<div class="row pt-2">
					<div class="col-6 col-md-3">
						<button type="submit" class="btn btn-success w-100">
							<i class="bi bi-check-circle"></i> Create
						</button>
					</div>
					<div class="col-6 col-md-3">
						<a asp-controller="Villa" asp-action="Index" class="btn btn-secondary w-100">
							<i class="bi bi-x-circle"></i> Cancel
						</a>
					</div>
				</div>
			</div>
		</form>
	</div>
</div>

@section Scripts{
@{
	<partial name="_ValidationScriptsPartial"/>
	}
}

AirBnb.web/Views/Villa/Delete.cshtml
@model AirBnb.Domain.Entities.Villa

<div class="w-100 card border-0 p-4">
	<div class="card-header bg-sucess bg-gradient m-lg-0 py-3">
		<div class="row">
			<div class="col-12 text-center">
				<h2 class="text-white py-2">Delete Villa</h2>
			</div>
		</div>
	</div>
	<div class="card-body border p-4">
		<form method="post" class="row" >
			<input asp-for="Id" hidden />
			<div class="col-10">
				<div class="p-3">
				<div class="form-floating py-1 col-12">
					<input asp-for="@Model.Name" disabled class="form-control border shadow" />
					<label asp-for="@Model.Name" class="ms-2"></label>
				</div>
				<div class="form-floating py-1 col-12">
					<input asp-for="@Model.Description" disabled class="form-control border shadow" />
					<label asp-for="@Model.Description" class="ms-2"></label>
				</div>
				<div class="form-floating py-1 col-12">
					<input asp-for="@Model.Price" disabled class="form-control border shadow" />
					<label asp-for="@Model.Price" class="ms-2"></label>
				</div>
				<div class="form-floating py-1 col-12">
					<input asp-for="@Model.Sqft" disabled class="form-control border shadow" />
					<label asp-for="@Model.Sqft" class="ms-2"></label>
				</div>
				<div class="form-floating py-1 col-12">
					<input asp-for="@Model.Occupancy" disabled class="form-control border shadow" />
					<label asp-for="@Model.Occupancy" class="ms-2"></label>
				</div>
				<div class="form-floating py-1 col-12">
					<input asp-for="@Model.ImageUrl" disabled class="form-control border shadow" />
					<label asp-for="@Model.ImageUrl" class="ms-2"></label>
				</div>
				<div class="row pt-2">
					<div class="col-6 col-md-3">
						<button type="submit" class="btn btn-danger w-100">
							<i class="bi bi-trash-fill"></i> Delete
						</button>
					</div>
					<div class="col-6 col-md-3">
						<a asp-controller="Villa" asp-action="Index" class="btn btn-secondary w-100">
							<i class="bi bi-x-circle"></i> Cancel
						</a>
					</div>
				</div>
			</div>
			</div>
			<div class="col-2">
				<img src="@Model.ImageUrl" width="100%"
					 style="border-radius:5px; border:1px solid #bbb9b9" />
			</div>
		</form>
	</div>
</div>

AirBnb.web/Views/Villa/Index.cshtml
@model IEnumerable<AirBnb.Domain.Entities.Villa>

<div class="w-100 card border-0 p-4">
	<div class="card-header bg-sucess bg-gradient m-lg-0 py-3">
		<div class="row">
			<div class="col-12 text-center">
				<h2 class="text-white py-2">Villa list</h2>
			</div>
		</div>
	</div>
</div>
<div class="card-body border p-4">
	<div class="row pb-3">
		<div class=col-6 offset-6 text-end">
			<a asp-controller="Villa" asp-action="Create" class="btn btn-secondary">
				<i class="bi bi-plus-circle"></i> Create New Villa
			</a>
		</div>
	</div>
	<table class="table table-bordered table-striped">
		<thead>
			<tr>
				<th>Name</th>
				<th>Price</th>
				<th>Sqft</th>
				<th>Occupancy</th>
				<th></th>
			</tr>
		</thead>
		<tbody>
			@foreach (var obj in Model)
			{
				<tr>
					<td>@obj.Name</td>
					<td>@obj.Price</td>
					<td>@obj.Sqft</td>
					<td>@obj.Occupancy</td>
					<td>
						<div class="w-75 btn-group" role="group">
							<a asp-action="Update" asp-controller="Villa" asp-route-VillaId="@obj.Id"
							class="btn btn-success mx-2">
								<i class="bi bi-pencil-square"></i>Edit</a>
							<a asp-action="Delete" asp-controller="Villa" asp-route-VillaId="@obj.Id"
							class="btn btn-danger mx-2">
								<i class="bi bi-trash-fill"></i>Delete
							</a>
						</div>
					</td>
				</tr>
			}
		</tbody>
	</table>
</div>

AirBnb.web/Views/Villa/Update.cshtml
@model AirBnb.Domain.Entities.Villa

<div class="w-100 card border-0 p-4">
	<div class="card-header bg-sucess bg-gradient m-lg-0 py-3">
		<div class="row">
			<div class="col-12 text-center">
				<h2 class="text-white py-2">Update Villa</h2>
			</div>
		</div>
	</div>
	<div class="card-body border p-4">
		<form method="post" class="row" enctype="multipart/form-data">
			<input asp-for="Id" hidden/>
			<div class="col-10">
				<div class="p-3">
					<div class="form-floating py-1 col-12">
						<input asp-for="@Model.Name" class="form-control border shadow" />
						<label asp-for="@Model.Name" class="ms-2"></label>
						<span asp-validation-for="@Model.Name" class="text-danger"></span>
					</div>
					<div class="form-floating py-1 col-12">
						<input asp-for="@Model.Description" class="form-control border shadow" />
						<label asp-for="@Model.Description" class="ms-2"></label>
						<span asp-validation-for="@Model.Description" class="text-danger"></span>
					</div>
					<div class="form-floating py-1 col-12">
						<input asp-for="@Model.Price" class="form-control border shadow" />
						<label asp-for="@Model.Price" class="ms-2"></label>
						<span asp-validation-for="@Model.Price" class="text-danger"></span>
					</div>
					<div class="form-floating py-1 col-12">
						<input asp-for="@Model.Sqft" class="form-control border shadow" />
						<label asp-for="@Model.Sqft" class="ms-2"></label>
						<span asp-validation-for="@Model.Sqft" class="text-danger"></span>
					</div>
					<div class="form-floating py-1 col-12">
						<input asp-for="@Model.Occupancy" class="form-control border shadow" />
						<label asp-for="@Model.Occupancy" class="ms-2"></label>
						<span asp-validation-for="@Model.Occupancy" class="text-danger"></span>
					</div>
					<div class="form-floating py-1 col-12">
						<input asp-for="@Model.Image" class="form-control border shadow" />
						<input asp-for="@Model.ImageUrl" hidden class="form-control border shadow" />
						<label asp-for="@Model.ImageUrl" class="ms-2"></label>
						<span asp-validation-for="@Model.ImageUrl" class="text-danger"></span>
					</div>
					<div class="row pt-2">
						<div class="col-6 col-md-3">
							<button type="submit" class="btn btn-success w-100">
								<i class="bi bi-check-circle"></i> Update
							</button>
						</div>
						<div class="col-6 col-md-3">
							<a asp-controller="Villa" asp-action="Index" class="btn btn-secondary w-100">
								<i class="bi bi-x-circle"></i> Cancel
							</a>
						</div>
					</div>
				</div>
			</div>
			<div class="col-2">
				<img src="@Model.ImageUrl" width="100%"
						style="border-radius:5px; border:1px solid #bbb9b9" />
			</div>
		</form>
	</div>
</div>

@section Scripts {
	@{
		<partial name="_ValidationScriptsPartial" />
	}
}